#%RAML 1.0
version: v1
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/1df5f454-84ef-427c-900c-a9da925c7a82/ # 
title: Multiply

/multiply:
  get:
    queryParameters:
      num1:
        type: number
        required: true
      num2:
        type: number
        required: true
    responses:
      200:
        body:
          application/json:
            example:
              {"message" : "multiply done"}

  post:
    body:
      application/json:
        example:
    responses:
      200:
        body:
          application/json:
            example:
              {"message" : "Numbers multiplied"}  